---
# tasks file for nodejs
- name: Install any necessary dependencies
  apt:
    name: "apt-transport-https"
    state: present
  become: true

- name: Add NodeJS apt key
  apt_key:
    url: "https://deb.nodesource.com/gpgkey/nodesource.gpg.key"
    id: 68576280
    state: present
  become: true

- name: Add NodeJS apt repository
  apt_repository:
    repo: "deb https://deb.nodesource.com/node_{{ nodejs_version }} {{ ansible_distribution_release }} main"
    update_cache: yes
    state: present
  become: true

- name: Install NodeJS
  apt:
    name: nodejs
    state: latest
    update_cache: yes
  become: true
